package main.java.com.football.test;


public class GenerateGames {
	private enum teams {
		ARGENTINOS_JRS, ESTUDIANTES_LP, GODOY_CRUZ, INDEPENDIENTE, BANFIELD, NO_BOYS, LANUS, RACING, VELEZ, HURACAN, TIGRE, GIMNASIA_ESGRIMA_LP, RIVER_PLATE, COLON, SAN_LORENZO, BOCA, ALL_BOYS, QUILMES, OLIMPO, ARSENAL
	};
	
}
